movies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('my_movies.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

my_movies/urls.py
"""Defines URL patterns for My movies"""

from django.urls import path
from . import views

app_name = 'my_movies'

urlpatterns = [
    path('', views.home, name='home'),
    path('all/', views.all, name='all'),
    path('last10/', views.last_added, name='last_added'),
    path('top10/', views.top10, name='top10'),
    path('by_user/', views.by_user, name='by_user'),
    path('my_movies/', views.my_movies, name='my_movies'),
    path('movies/author<owner>/', views.user_movies, name='user_movies'),
    path('movies/<int:movie_id>/', views.movie, name='movie'),
    path('movies/comments/<int:movie_id>/', views.see_comments, name='see_comments'),
    path('find/<int:db_id>/', views.find, name='find'),
    path('add_post/', views.add, name='add'),
    path('movies/<int:movie_id>/delete/', views.delete, name='delete'),
    path('edit/<int:movie_id>/', views.edit, name='edit'),
    path('new_comment/<int:movie_id>/', views.new_comment, name='new_comment'),
    path('not_tmdb/', views.not_tmdb, name="not_tmdb"),
    path('wish_list/', views.wish_list, name="wish_list"),
    path('watch_list/<int:movie_id>', views.add_to_watchlist, name="add_to_watchlist"),
    path('favorite/', views.favorite, name="favorite"),
    path('favorite/<int:movie_id>', views.delete_from_watchlist, name="delete_from_watchlist"),
    path('note/<int:note_id>', views.delete_note, name="delete_note"),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('login_check/', views.login_check, name='login_check'),
]

my_movies/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator



# Create your models here.
class Movie(models.Model):
    """movie data"""
    title = models.CharField(max_length=200)
    year = models.IntegerField(null=True, blank=True)
    genre = models.CharField(max_length=200, null=True, blank=True)
    description = models.CharField(null=True, blank=True, max_length=2500)
    rating = models.FloatField(null=True, blank=True)
    review = models.CharField(null=True, blank=True, max_length=2500)
    img_url = models.URLField(null=True, blank=True, max_length=2000)
    homepage = models.URLField(null=True, blank=True, max_length=2000)

    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    fan = models.ManyToManyField(User, related_name="fan")

    def __str__(self):
        """return model as a string"""
        return self.title


class Comment(models.Model):
    """users' comments"""
    text = models.TextField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'comments'

    def __str__(self):
        """model as a string"""
        return f"{self.text}"


class Note(models.Model):
    """watchlist items"""
    title = models.CharField(max_length=200)
    comment = models.CharField(max_length=500)
    rating = models.FloatField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """return model as a string"""
        return self.title

my_movies/forms.py
from django import forms
from .models import Movie, Comment, Note


class MovieForm(forms.ModelForm):
    rating = forms.FloatField(max_value=10, min_value=0,
                              widget=forms.NumberInput(attrs={'step': "0.5"}))

    class Meta:
        model = Movie
        fields = ['title', 'rating', 'review', 'year', 'description', 'homepage', 'img_url']
        widgets = {'review': forms.Textarea(attrs={'class': 'form-control form-control-lg', 'cols': 60}),
                   'description': forms.Textarea(attrs={'class': 'form-control form-control-lg', 'cols': 60}),
                   }


class AddForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['title']


class ReviewForm(forms.ModelForm):
    rating = forms.FloatField(required=True, max_value=10, min_value=0,
                              widget=forms.NumberInput(attrs={'step': "0.5"}))

    class Meta:
        model = Movie
        fields = ['rating', 'review']
        widgets = {'review': forms.Textarea(
            attrs={'class': 'form-control form-control-lg',
                   'cols': 60,
                   'required': True})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(
            attrs={'class': 'form-control form-control-lg', 'cols': 80})
        }


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'rating']

my_movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Movie, Comment, Note
from django.contrib.auth.models import User
from .forms import MovieForm, CommentForm, ReviewForm, AddForm, NoteForm

import requests

TMDB_ENDPOINT = "https://api.themoviedb.org/3/search/movie"
TMDB_Key = 'cc543d2d9414e851a83e46e2fa1a5a57'
TMDB_IMG = "https://image.tmdb.org/t/p/w500"


def home(request):
    movies = Movie.objects.order_by('-date_added')[:1]
    context = {'movies': movies}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/home.html', context)
    else:
        return render(request, 'uk_movies/home.html', context)


def all(request):
    movies = Movie.objects.order_by('-rating')
    context = {'movies': movies}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/index.html', context)
    else:
        return render(request, 'uk_movies/index.html', context)



def last_added(request):
    movies = Movie.objects.order_by('-date_added')[:10]
    context = {'movies': movies}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/index.html', context)
    else:
        return render(request, 'uk_movies/index.html', context)



def top10(request):
    movies = Movie.objects.order_by('-rating')[:10]
    language = request.LANGUAGE_CODE
    if language == "en":
        heading = "TOP 10 by Rating"
        context = {'movies': movies, 'heading': heading}
        return render(request, 'my_movies/index.html', context)
    else:
        heading = "ТОП-10 за рейтингом"
        context = {'movies': movies, 'heading': heading}
        return render(request, 'uk_movies/index.html', context)



def by_user(request):
    users = User.objects.all()
    context = {'users': users}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/by_user.html', context)
    else:
        return render(request, 'uk_movies/by_user.html', context)


@login_required
def my_movies(request):
    movies = Movie.objects.filter(owner=request.user).order_by('-date_added')
    context = {'movies': movies, 'owner': request.user}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/all_movies.html', context)
    else:
        return render(request, 'uk_movies/all_movies.html', context)


def user_movies(request, owner):
    movies = Movie.objects.filter(owner__username=owner).order_by('-date_added')
    context = {'movies': movies, 'owner': owner}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/all_movies.html', context)
    else:
        return render(request, 'uk_movies/all_movies.html', context)


def movie(request, movie_id):
    """Show a single movie and all its comments"""
    movie = get_object_or_404(Movie, id=movie_id)
    comments = Comment.objects.filter(movie=movie, parent=None).order_by('-date_added')
    replies = Comment.objects.filter(movie=movie).exclude(parent=None).order_by('-date_added')

    context = {'movie': movie, 'comments': comments, 'replies': replies}

    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/movie.html', context)
    else:
        return render(request, 'uk_movies/movie.html', context)


@login_required()
def add(request):
    """add new post"""
    if request.method != 'POST':
        form = AddForm()
    else:
        form = AddForm(data=request.POST)
        if form.is_valid():
            title = request.POST['title']
            request.session['title'] = title

            response = requests.get("https://api.themoviedb.org/3/search/movie",
                                    params={"api_key": TMDB_Key, "query": title})
            tmdb_movies = response.json()['results']
            context = {'movies': tmdb_movies, 'title': title}
            language = request.LANGUAGE_CODE
            if language == "en":
                return render(request, 'my_movies/select.html', context)
            else:
                return render(request, 'uk_movies/select.html', context)

    context = {'form': form}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/add.html', context)
    else:
        return render(request, 'uk_movies/add.html', context)



@login_required
def find(request, db_id):
    """get TMDB movie details"""
    response = requests.get(f"https://api.themoviedb.org/3/movie/{db_id}", params={'api_key': TMDB_Key})
    selected_movie = response.json()

    try:
        genre_db = selected_movie['genres'][0]['name']
    except IndexError:
        genre_db = None

    year_year = selected_movie['release_date'].split("-")[0]

    new_movie = Movie(
        title=selected_movie['title'],
        owner=request.user,
        year=year_year,
        description=selected_movie['overview'],
        homepage=selected_movie['homepage'],
        img_url=f"{TMDB_IMG}{selected_movie['poster_path']}",
        genre=genre_db,
    )

    movie = new_movie
    if movie.owner != request.user:
        raise Http404
    if request.method != 'POST':
        review_form = ReviewForm(instance=movie)
    else:
        review_form = ReviewForm(instance=movie, data=request.POST)
        if review_form.is_valid():
            movie.review = request.POST['review']
            movie.rating = request.POST['rating']
            try:
                movie.save()
            except ValueError:
                movie.year = None
                movie.save()

            return redirect('my_movies:my_movies')

    context = {'movie': movie, 'form': review_form}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/review.html', context)
    else:
        return render(request, 'uk_movies/review.html', context)



@login_required
def not_tmdb(request):
    title = request.session['title']
    if request.method != "POST":
        form = ReviewForm()
    else:
        form = ReviewForm(data=request.POST)
        if form.is_valid():
            new_movie = form.save(commit=False)
            new_movie.owner = request.user
            new_movie.title = title
            new_movie.save()
            return redirect('my_movies:home')
    context = {'form': form, 'title': title}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/not_tmdb.html', context)
    else:
        return render(request, 'uk_movies/not_tmdb.html', context)



@login_required
def edit(request, movie_id):
    """edit movie's info"""
    movie = Movie.objects.get(id=movie_id)
    if movie.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = MovieForm(instance=movie)
    else:
        form = MovieForm(instance=movie, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('my_movies:movie', movie_id=movie.id)

    context = {'movie': movie, 'form': form}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/edit.html', context)
    else:
        return render(request, 'uk_movies/edit.html', context)



@login_required
def delete(request, movie_id):
    """delete movie"""
    movie = Movie.objects.get(id=movie_id)
    if movie.owner != request.user:
        raise Http404
    movie.delete()
    return redirect('my_movies:my_movies')


@login_required
def new_comment(request, movie_id):
    """add a new comment for a particular movie"""
    movie = Movie.objects.get(id=movie_id)

    if request.method != 'POST':
        # create an empty form
        form = CommentForm()
    else:
        parent_id = request.POST.get('parentId')
        if parent_id:
            parent = Comment.objects.get(id=parent_id)
            text = request.POST.get('reply')
            comment_reply = Comment(text=text, owner=request.user, movie=movie, parent=parent)
            comment_reply.save()
        else:
            form = CommentForm(data=request.POST)

            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.movie = movie
                new_comment.owner = request.user
                new_comment.save()

        return redirect("my_movies:see_comments", movie_id=movie_id)

    # show an empty form
    context = {'movie': movie, 'form': form}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/new_comment.html', context)
    else:
        return render(request, 'uk_movies/new_comment.html', context)



@login_required
def see_comments(request, movie_id):
    """Show all comments to a particular movie"""
    movie = Movie.objects.get(id=movie_id)

    comments = Comment.objects.filter(movie=movie, parent=None).order_by('-date_added')
    replies = Comment.objects.filter(movie=movie).exclude(parent=None).order_by('-date_added')
    replyDict = {}
    for reply in replies:
        if reply.parent.id not in replyDict.keys():
            replyDict[reply.parent.id] = [reply]
        else:
            replyDict[reply.parent.id].append(reply)

    context = {'movie': movie, 'comments': comments, 'replies': replies, 'replyDict': replyDict}
    language = request.LANGUAGE_CODE
    if language == "en":
        return render(request, 'my_movies/comments.html', context)
    else:
        return render(request, 'uk_movies/comments.html', context)



@login_required
def wish_list(request):
    favourite_movies = Movie.objects.filter(fan=request.user).order_by('-date_added')
    my_notes = Note.objects.filter(owner=request.user).order_by('-rating')
    context = {'movies': favourite_movies, 'notes': my_notes}
    language = request.LANGUAGE_CODE

my_movies/templates/my_movies/add.html
{% extends 'my_movies/base.html' %}

{% block content %}
<h3>Add new post</h3>
<form action="{% url 'my_movies:add' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add movie</button>
</form>
{% endblock content %}

my_movies/templates/my_movies/base.html
{% load bootstrap5 %}



<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial=scale=1, shrink-to-fit=no">
    <link rel=”stylesheet” href=”https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css” />


    <title>My movies</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}


</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">

    <a class="navbar-brand" href="{% url 'my_movies:home' %}">My Family Cinema</a>

    <a class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" >
        <span class="navbar-toggler-icon"></span>
    </a>

    <div class="collapse navbar-collapse" id="navbarCollapse">

    <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="btn btn-outline-success" type="submit" href="{% url 'my_movies:add' %}">
                    Add post
                </a>
            </li>
    </ul>

        <ul class="navbar-nav ms-auto">
          {% if not user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
            </li>
            {% else %}
            <li class="nav-item navbar-text">
                {{ user.username }}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my_movies:my_movies' %}">My Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my_movies:wish_list' %}">WatchList</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout'%}">Log out</a>
            </li>

          {% endif %}
        </ul>
    </div>
</nav>

<main role="main" class="container">
    <div class="pb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>

</main>

</body>
</html>

my_movies/templates/my_movies/by_user.html
{% extends 'my_movies/base.html' %}

{% block page_header %}
<h1>Our users recommend</h1>
{% endblock page_header %}

{% block content %}

{% for user in users %}
{% if not user.is_superuser %}
<p>
<h3><a class="link-success text-decoration-none" href="{% url 'my_movies:user_movies' user %}">Movies from <b><i>{{ user }}</i></b></a></h3>
</p>
{% endif %}
{% endfor %}


{% endblock %}

my_movies/templates/my_movies/comments.html
{% extends 'my_movies/base.html' %}
{% load extras %}

{% block page_header %}

{% endblock page_header %}

{% block content %}

      <div>
        <a class="link-dark" href="{% url 'my_movies:movie' movie.id %}"><h3>{{ movie }}</h3></a><h4>&#11088 {{ movie.rating }}</h4>
      </div>

  {% for comment in comments %}
    <div class="row" style="margin-top:10px;">

      <div class="col-2">
        <img class="rounded mx-auto d-block w-75 border border-dark p-2" src="https://styles.redditmedia.com/t5_2qqcn/styles/communityIcon_de3pi2i14o551.png" alt="user profile img">
      </div>

      <div class="col-10">
        <b> {{comment.owner}} </b> {{ comment.date_added|date:'M d, Y H:i'}}
        <p>{{comment}}</p>


          <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#renderForm">
            Reply
          </button>

          <a data-bs-toggle="collapse" data-bs-target="#repls">
            Replies
          </a>

          {% for reply in replyDict|get_val:comment.id %}


            <div class="row" style="margin-top:15px;">
              <div class="collapse" id="repls">
              <div class="col">
                <b>{{ reply.owner }}</b> {{ reply.date_added|date:'M d, Y H:i'}}
                <p>{{ reply }}</p>
              </div>
              </div>
            </div>

         {% endfor %}
      </div>

      <div class="collapse" id="renderForm">
        <div class="card card-body my-2">
          <form action="{% url 'my_movies:new_comment' movie.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div>
              <label for="comment">Post a reply </label>
              <input type="text" class="form-control" id="comment" name="reply" placeholder="Enter comment here">
              <input type="hidden" name="parentId" value="{{comment.id}}">
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Submit</button>
          </form>

        </div>
      </div>
    </div>

 {% empty %}
      <p>
        There are no comments for this movie yet.
      </p>
 {% endfor %}

<div style="margin-top:15px">
<a class="btn btn-success" href="{% url 'my_movies:new_comment' movie.id %}">New Comment</a>
</div>
{% endblock %}

my_movies/templates/my_movies/edit.html
{% extends 'my_movies/base.html'%}


{% block content %}
<h1><a href="{% url 'my_movies:movie' movie.id %}">{{ movie }}</a></h1>

<form action="{% url 'my_movies:edit' movie.id %}" method='post'>
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

my_movies/templates/my_movies/favorite.html
{% extends "my_movies/base.html" %}

{% block content %}

<form action="{% url 'my_movies:favorite' %}" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <button name="submit">Add</button>
</form>






{% endblock content %}

my_movies/templates/my_movies/home.html
{% extends "my_movies/base.html" %}
{% load static %}

{% block page_header %}

<h1>What to watch</h1>

{% endblock page_header %}

{% block content %}

<div class="container" style="padding:0px 20px">

<div class=container" style="padding:15px 15px">
<a class="link-dark" href="{% url 'my_movies:top10' %}"><h3>Top 10</h3></a>
</div>
<div class=container" style="padding:15px 15px">
<a class="link-dark" href="{% url 'my_movies:by_user' %}"><h3>by User</h3></a>
</div>
<div class=container" style="padding:15px 15px">
<a class="link-dark" href="{% url 'my_movies:last_added' %}"><p class="h3">Last added</p></a>
</div>
<div class=container" style="padding:15px 15px">
<a class="link-dark" href="{% url 'my_movies:all' %}"><p class="h3">All movies</p></a>
</div>

</div>

<hr>

{% endblock content %}

my_movies/templates/my_movies/new_comment.html
{% extends 'my_movies/base.html' %}

{% block content %}

<p> <a href="{% url 'my_movies:movie' movie.id %}">{{ movie }}</a></p>
<p>Add a new comment</p>
<form action="" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="parentId" value="{{comment.id}}">
    <button name='submit'>Submit</button>
</form>


{% endblock content %}

my_movies/templates/my_movies/not_tmdb.html
{% extends 'my_movies/base.html' %}

{% block content %}

<p class="h3">Title: {{ title.title }}</p>

<form action="{% url 'my_movies:not_tmdb' %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button class='btn btn-primary' name="submit">Add movie</button>
</form>

{% endblock content %}

my_movies/templates/my_movies/review.html
{% extends 'my_movies/base.html'%}
{% load bootstrap5 %}


{% block content %}
<h1>{{ movie }}</h1>

<form action="" method='post'>
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

my_movies/templates/my_movies/select.html
{% extends 'my_movies/base.html' %}
{% load extras %}

{% block content%}

<div>
  {% if movies %}
  <h2>Choose a movie from our list <b>or</b> add a movie manually
    <a class="btn btn-outline-success" href="{% url 'my_movies:not_tmdb'  %}">Add manually</a>
  </h2>
  {% else %}
  <h2>We didn't find a movie with title <b>{{ title }}</b> but you can add a movie manually
    <a class="btn btn-outline-success" href="{% url 'my_movies:not_tmdb'  %}">Add manually</a>
  </h2>
  {% endif %}

</div>
{% for movie in movies %}
<div class="row" style="padding:10px">
  <div class="col-4">
    <img src="https://image.tmdb.org/t/p/w500{{movie.poster_path}}" class="image-responsive" width="70%">
  </div>
  <div class="col-8">
    <div>
      <p>
        <b>{{ movie.title }}</b>
      </p>
      <p>
        <a class="btn btn-outline-success" href="{% url 'my_movies:find' movie.id %}">Add</a>
      </p>
    </div>
  </div>
</div>
{% endfor %}

{% endblock content %}

my_movies/templates/my_movies/wish_list.html
{% extends 'my_movies/base.html'%}
{% load bootstrap5 %}

{% block page_header %}
<h3>My WatchList</h3>
{% endblock %}

{% block content %}
<div class="pad-5">
<h4>Movies from <a class="link-dark" href="{% url 'my_movies:home' %}">My Family Cinema</a></h4>
</div>
<div class="container" style="padding-bottom:35px">
  {% for movie in movies %}
  <div class="row">
    <div class="col">
      <ul class="list-group">
        <li class="list-group-item list-group-item-secondary
        d-flex justify-content-between align-items-center">
          <a class="link-success" href="{% url 'my_movies:movie' movie.id %}">{{ movie }} (<i>from {{ movie.owner }})</i></a>
          <span class="badge"><a class="btn-outline-danger" href="{% url 'my_movies:delete_from_watchlist' movie.id %}">☓</a></span>
        </li>
      </ul>
    </div>
  </div>
  {% empty %}
  <p>There are not movies in your WatchList yet</p>
  {% endfor%}
</div>

<hr>
<div class="container" style="padding-bottom:35px">
  <h4>My Notes</h4>

  {% for note in notes %}
  <div class="row">
    <div class="col">
      <ul class="list-group">
        <li class="list-group-item list-group-item-success
        d-flex justify-content-between align-items-center">
          {{ note }}
          <span class="badge"><a class="btn-outline-danger" href="{% url 'my_movies:delete_note' note.id %}">☓</a></span>
        </li>
      </ul>
    </div>
  </div>
  {% empty %}
  <p>There are not notes in your WatchList yet</p>
  {% endfor %}
</div>
<div>
  <a class="btn btn-outline-success" href="{% url 'my_movies:favorite' %}">Add a note</a>
</div>
<hr>









{% endblock content %}